In [12]:
import pandas as pd
import glob

### Node-Groups
Contains the hardware characteristics and information about the physical nodes in the IFCA Cloud infrastructure.

The `node_group` of the physical nodes is equivalent to the `hypervisor_group` of the virtual machines running in them.

In [8]:
node_groups = pd.read_csv("../datasets/cloud_energy_consumption/node-groups/2024-12-14T000000Z_2025-04-13T235959Z/groups.csv")
node_groups.head(6)

,node_group,model,form_factor,#sockets,cpu,#cores_per_socket,#threads_per_core,memory_type,memory_manufacturer,memory_used_slots,...,#infiniband_nics,infiniband_nic_model,#disks,disk_vendor,disk_model,disk_type,disk_size_GB,#fans,#power_supplies,rated_power
0,11cdff15,Fujitsu Server PRIMERGY BX924 S4,Blade Server,2,Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz,12,2,DDR3,Hyundai Electronics (Hynix),1,...,0,-,1,Intel,INTEL_SSDSC2BA400G3C1,SSD,400.00,12 (per chassis),2 (per chassis),3200 W / 1600 W
1,b8994569,Lenovo ThinkSystem SD530,Chassis Server,2,Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz,24,2,DDR4,Samsung,6,...,0,-,1,Samsung,MZ7LH480HAHQ-000V3_01PE095D7A09572LEN,SSD,480.00,10 (per 4 nodes),2 (per 4 nodes),2000 W
2,a97fe24e,Lenovo ThinkSystem SR630,Rack Server,2,Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz,20,2,DDR4,Micron Technology,12,...,0,-,2,Lenovo,NaN,SSD,223.50,14,2,750 W
3,5f67cb23,Lenovo ThinkSystem SR650,Rack Server,2,Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz,20,2,DDR4,SK Hynix,12,...,1,Mellanox MT27800 Family [ConnectX-5],2,Micron,MTFDDAK1T9TDC-1AT1ZA,SSD,1966.08,6,2,1600 W
4,f6fec747,Dell Inc. PowerEdge C6420,Chassis Server,2,Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz,24,2,DDR4,002C069D002C,6,...,0,-,4,DELL,MZ7LH480HBHQ0D3,SSD,446.63,8,2 (per 4 nodes),2400 W
5,a6177608,Lenovo ThinkSystem SR630 V2,Rack Server,2,Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz,32,2,DDR4,Samsung,12,...,1,Mellanox MT28908 Family [ConnectX-6],2,Lenovo,MTFDDAV960TDS-1AW1ZA,M.2 SATA SSD,960.00,16,1,1100 W

In [6]:
node_groups.shape

(6, 25)

### VMs 
Hardware characteristics and information about the virtual machines in the IFCA Cloud infrastructure, including their user and project information.

The `vm_id` of the virtual machines in this dataset is equivalent to the `vm_id` of the virtual machines in the "Virtual Machines energy consumption metrics" dataset. The `project_id` and `user_id` of the virtual machines in this dataset are used to identify the project and user associated with them.

In [ ]:
vm_hardware = pd.read_csv("../datasets/cloud_energy_consumption/vms/2024-12-14T000000Z_2025-04-13T235959Z/vms.csv")
print(vm_hardware.shape)

(611, 8)

In [10]:
vm_hardware.head(10)

,vm_id,user_id,project_id,image_ref,vcpus,memory_mb,root_gb,ephemeral_gb
0,6239bcf4,39786247,4ba6ce42,85ecdff4,32.0,60000.0,30.0,160.0
1,80458243,bd41a7e4,74dfdf00,cb92696e,1.0,2000.0,10.0,20.0
2,5d9f6237,7190ddfa,906147a9,78c5906a,4.0,7500.0,30.0,60.0
3,941785dc,1a324c91,f09054da,23658854,2.0,4000.0,10.0,100.0
4,fb856e0f,c1eb1c1c,f09054da,c015d680,4.0,7500.0,30.0,60.0
5,2d329ea1,167938a6,6b583f77,3a487497,4.0,7500.0,30.0,60.0
6,6818d80c,933a1206,70ce18f7,c47411e7,3500.0,30.0,40.0,NaN
7,46e19c93,933a1206,70ce18f7,c47411e7,3500.0,30.0,40.0,NaN
8,8e62a0df,933a1206,70ce18f7,a1beddaf,15000.0,30.0,60.0,NaN
9,5ae95310,933a1206,70ce18f7,c47411e7,3500.0,30.0,40.0,NaN

### Nodes

#### Power Consumption
- IPMI Power Consumption Metrics
- RAPL Power Consumption Metrics
- Scaphandre Power Consumption Metrics

In [14]:
node_files = glob.glob("../datasets/cloud_energy_consumption/nodes/2024-12-14T000000Z_2025-04-13T235959Z/**/*.csv")
print(f"Number of node files: {len(node_files)}")

Number of node files: 130

In [15]:
all_nodes = pd.concat((pd.read_csv(f) for f in node_files), ignore_index=True)
print(all_nodes.shape)
all_nodes.head(10)

(7434114, 51)

,timestamp,node_name,node_group,cpu_usage_percent,cpu_idle_percent,cpu_nice_percent,cpu_interrupt_percent,cpu_softirq_percent,cpu_steal_percent,cpu_system_percent,...,rapl_power_cores_0_watts,rapl_power_cores_1_watts,scaphandre_power_total_watts,ipmi_cpu_power_watts,ipmi_memory_power_watts,ipmi_fan_power_watts,ipmi_psu1_ac_in_power_watts,ipmi_psu2_ac_in_power_watts,ipmi_psu1_dc_out_power_watts,ipmi_psu2_dc_out_power_watts
0,2024-12-14T00:00:00Z,cfc400f1,11cdff15,51.05,48.95,0.03,0.0,0.02,0.0,1.05,...,90.15,91.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-12-14T00:03:00Z,cfc400f1,11cdff15,63.98,36.02,0.00,0.0,0.04,0.0,3.29,...,92.45,92.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-12-14T00:06:00Z,cfc400f1,11cdff15,65.05,34.95,0.00,0.0,0.07,0.0,2.21,...,92.88,92.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-12-14T00:09:00Z,cfc400f1,11cdff15,52.64,47.36,0.00,0.0,0.09,0.0,2.40,...,90.08,89.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-12-14T00:12:00Z,cfc400f1,11cdff15,56.14,43.86,0.03,0.0,0.07,0.0,2.51,...,89.73,89.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2024-12-14T00:15:00Z,cfc400f1,11cdff15,66.09,33.91,0.00,0.0,0.07,0.0,2.26,...,93.90,91.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024-12-14T00:18:00Z,cfc400f1,11cdff15,54.58,45.42,0.00,0.0,0.08,0.0,2.24,...,91.63,89.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-12-14T00:21:00Z,cfc400f1,11cdff15,56.85,43.15,0.00,0.0,0.07,0.0,1.96,...,91.55,89.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-12-14T00:24:00Z,cfc400f1,11cdff15,53.17,46.83,0.00,0.0,0.08,0.0,2.02,...,89.88,90.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-12-14T00:27:00Z,cfc400f1,11cdff15,54.44,45.56,0.00,0.0,0.06,0.0,2.03,...,90.13,89.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
all_nodes.head(100)

,timestamp,node_name,node_group,cpu_usage_percent,cpu_idle_percent,cpu_nice_percent,cpu_interrupt_percent,cpu_softirq_percent,cpu_steal_percent,cpu_system_percent,...,rapl_power_cores_0_watts,rapl_power_cores_1_watts,scaphandre_power_total_watts,ipmi_cpu_power_watts,ipmi_memory_power_watts,ipmi_fan_power_watts,ipmi_psu1_ac_in_power_watts,ipmi_psu2_ac_in_power_watts,ipmi_psu1_dc_out_power_watts,ipmi_psu2_dc_out_power_watts
0,2024-12-14T00:00:00Z,cfc400f1,11cdff15,51.05,48.95,0.03,0.0,0.02,0.0,1.05,...,90.15,91.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-12-14T00:03:00Z,cfc400f1,11cdff15,63.98,36.02,0.00,0.0,0.04,0.0,3.29,...,92.45,92.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-12-14T00:06:00Z,cfc400f1,11cdff15,65.05,34.95,0.00,0.0,0.07,0.0,2.21,...,92.88,92.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-12-14T00:09:00Z,cfc400f1,11cdff15,52.64,47.36,0.00,0.0,0.09,0.0,2.40,...,90.08,89.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-12-14T00:12:00Z,cfc400f1,11cdff15,56.14,43.86,0.03,0.0,0.07,0.0,2.51,...,89.73,89.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-12-14T04:45:00Z,cfc400f1,11cdff15,50.90,49.10,0.00,0.0,0.04,0.0,1.54,...,87.91,89.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,2024-12-14T04:48:00Z,cfc400f1,11cdff15,54.25,45.75,0.00,0.0,0.06,0.0,1.14,...,87.71,89.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,2024-12-14T04:51:00Z,cfc400f1,11cdff15,65.56,34.44,0.00,0.0,0.04,0.0,1.14,...,93.66,91.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,2024-12-14T04:54:00Z,cfc400f1,11cdff15,64.79,35.21,0.00,0.0,0.04,0.0,1.03,...,93.99,91.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,2024-12-14T04:57:00Z,cfc400f1,11cdff15,65.04,34.96,0.02,0.0,0.04,0.0,1.02,...,93.57,92.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Summary Checks

In [20]:
for df, name in [(node_groups, "Nodes Hardware Data"), (all_nodes, "All Nodes Data"), (vm_hardware, "VM Hardware Data")]:
    print(f"\n=== {name} ===")
    print("Shape of the DataFrame:", df.shape)
    print("\n=== Data types of each column: ===")
    print(df.dtypes)
    print("\n=== Summary statistics: ===")
    print(df.describe())

=== Nodes Hardware Data ===
Shape of the DataFrame: (6, 25)

=== Data types of each column: ===
node_group                  str
model                       str
form_factor                 str
#sockets                  int64
cpu                         str
#cores_per_socket         int64
#threads_per_core         int64
memory_type                 str
memory_manufacturer         str
memory_used_slots         int64
memory_total_size_GB    float64
#gpus                     int64
#gpu_model                  str
#ethernet_nics            int64
ethernet_nic_model          str
#infiniband_nics          int64
infiniband_nic_model        str
#disks                    int64
disk_vendor                 str
disk_model                  str
disk_type                   str
disk_size_GB            float64
#fans                       str
#power_supplies             str
rated_power                 str
dtype: object

=== Summary statistics: ===
       #sockets  #cores_per_socket  #threads_per_core  memory_used_slots  \
count       6.0           6.000000                6.0           6.000000
mean        2.0          22.000000                2.0           8.166667
std         0.0           6.572671                0.0           4.578937
min         2.0          12.000000                2.0           1.000000
25%         2.0          20.000000                2.0           6.000000
50%         2.0          22.000000                2.0           9.000000
75%         2.0          24.000000                2.0          12.000000
max         2.0          32.000000                2.0          12.000000

       memory_total_size_GB     #gpus  #ethernet_nics  #infiniband_nics  \
count              6.000000  6.000000             6.0          6.000000
mean             290.666667  0.333333             2.0          0.333333
std              261.229912  0.816497             0.0          0.516398
min               16.000000  0.000000             2.0          0.000000
25%              192.000000  0.000000             2.0          0.000000
50%              192.000000  0.000000             2.0          0.000000
75%              336.000000  0.000000             2.0          0.750000
max              768.000000  2.000000             2.0          1.000000

         #disks  disk_size_GB
count  6.000000      6.000000
mean   2.000000    746.035000
std    1.095445    646.141137
min    1.000000    223.500000
25%    1.250000    411.657500
50%    2.000000    463.315000
75%    2.000000    840.000000
max    4.000000   1966.080000

=== All Nodes Data ===
Shape of the DataFrame: (7434114, 51)

=== Data types of each column: ===
timestamp                           str
node_name                        object
node_group                          str
cpu_usage_percent               float64
cpu_idle_percent                float64
cpu_nice_percent                float64
cpu_interrupt_percent           float64
cpu_softirq_percent             float64
cpu_steal_percent               float64
cpu_system_percent              float64
cpu_user_percent                float64
cpu_wait_percent                float64
load_shortterm_percent          float64
load_midterm_percent            float64
load_longterm_percent           float64
num_processes_total             float64
num_processes_blocked           float64
num_processes_paging            float64
num_processes_running           float64
num_processes_sleeping          float64
num_processes_stopped           float64
num_processes_zombie            float64
memory_total_bytes              float64
memory_free_bytes               float64
memory_used_bytes               float64
memory_buffered_bytes           float64
memory_cached_bytes             float64
memory_slab_recl_bytes          float64
memory_slab_unrecl_bytes        float64
disk_total_bytes                float64
disk_free_bytes                 float64
disk_used_bytes                 float64
disk_reserved_bytes             float64
network_bw_rx_b/s               float64
network_bw_tx_b/s               float64
ipmi_system_power_watts         float64
rapl_power_total_watts          float64
rapl_power_package_0_watts      float64
rapl_power_package_1_watts      float64
rapl_power_dram_0_watts         float64
rapl_power_dram_1_watts         float64
rapl_power_cores_0_watts        float64
rapl_power_cores_1_watts        float64
scaphandre_power_total_watts    float64
ipmi_cpu_power_watts            float64
ipmi_memory_power_watts         float64
ipmi_fan_power_watts            float64
ipmi_psu1_ac_in_power_watts     float64
ipmi_psu2_ac_in_power_watts     float64
ipmi_psu1_dc_out_power_watts    float64
ipmi_psu2_dc_out_power_watts    float64
dtype: object

=== Summary statistics: ===
       cpu_usage_percent  cpu_idle_percent  cpu_nice_percent  \
count       6.997389e+06      6.997389e+06      6.997389e+06
mean        6.880783e+00      9.311922e+01      2.422904e-03
std         1.848380e+01      1.848380e+01      1.691712e-02
min         0.000000e+00      0.000000e+00      0.000000e+00
25%         9.000000e-02      9.886000e+01      0.000000e+00
50%         2.900000e-01      9.971000e+01      0.000000e+00
75%         1.140000e+00      9.991000e+01      0.000000e+00
max         1.000000e+02      1.000000e+02      6.500000e+00

       cpu_interrupt_percent  cpu_softirq_percent  cpu_steal_percent  \
count              6997389.0         6.997389e+06          6997389.0
mean                     0.0         1.529287e-02                0.0
std                      0.0         3.961766e-02                0.0
min                      0.0         0.000000e+00                0.0
25%                      0.0         0.000000e+00                0.0
50%                      0.0         0.000000e+00                0.0
75%                      0.0         1.000000e-02                0.0
max                      0.0         2.120000e+00                0.0

       cpu_system_percent  cpu_user_percent  cpu_wait_percent  \
count        6.997389e+06      6.997389e+06      6.997389e+06
mean         3.171064e-01      6.525500e+00      1.938218e-02
std          1.741780e+00      1.818679e+01      6.139832e-01
min          0.000000e+00      0.000000e+00     -0.000000e+00
25%          3.000000e-02      5.000000e-02      0.000000e+00
50%          7.000000e-02      1.800000e-01      0.000000e+00
75%          2.000000e-01      7.600000e-01      0.000000e+00
max          5.520000e+01      9.999000e+01      7.287000e+01

       load_shortterm_percent  ...  rapl_power_cores_0_watts  \
count            6.997446e+06  ...             544169.000000
mean             6.755651e+00  ...                 34.564923
std              1.958311e+01  ...                 32.748515
min              0.000000e+00  ...                  4.800000
25%              1.000000e-01  ...                  6.780000
50%              3.000000e-01  ...                  9.230000
75%              1.240000e+00  ...                 64.800000
max              1.658600e+02  ...                387.620000

       rapl_power_cores_1_watts  scaphandre_power_total_watts  \
count             544169.000000                  4.907616e+06
mean                  35.158826                  1.903624e+02
std                   33.630168                  1.151281e+02
min                    4.390000                  2.060000e+00
25%                    6.080000                  6.374000e+01
50%                    8.290000                  2.618400e+02
75%                   64.950000                  2.705500e+02
max                  321.510000                  6.677300e+02

       ipmi_cpu_power_watts  ipmi_memory_power_watts  ipmi_fan_power_watts  \
count          5.867253e+06             5.867243e+06          4.908680e+06
mean           1.949945e+02             1.943804e+01          1.818682e+01
std            1.064912e+02             8.459388e+00          1.130435e+01
min            2.000000e+01             1.000000e+00          0.000000e+00
25%            5.867000e+01             1.150000e+01          1.500000e+01
50%            2.413300e+02             2.333000e+01          1.600000e+01
75%            2.480000e+02             2.600000e+01          1.800000e+01
max            6.750000e+02             7.017000e+01          1.020000e+02

       ipmi_psu1_ac_in_power_watts  ipmi_psu2_ac_in_power_watts  \
count                 4.908679e+06                 4.908682e+06
mean                  3.563463e+02                 3.305085e+01
std                   1.515655e+02                 6.144554e+01
min                   4.000000e+01                 0.000000e+00
25%                   2.175000e+02                 0.000000e+00
50%                   4.083300e+02                 0.000000e+00
75%                   4.191700e+02                 4.500000e+01
max                   8.766700e+02                 4.633300e+02

       ipmi_psu1_dc_out_power_watts  ipmi_psu2_dc_out_power_watts
count                  4.908683e+06                  4.908683e+06
mean                   3.349047e+02                  3.016875e+01
std                    1.447503e+02                  5.665666e+01
min                    3.083000e+01                  0.000000e+00
25%                    2.083300e+02                  0.000000e+00
50%                    3.850000e+02                  0.000000e+00
75%                    3.950000e+02                  3.583000e+01
max                    8.816700e+02                  4.400000e+02

[8 rows x 48 columns]

=== VM Hardware Data ===
Shape of the DataFrame: (611, 8)

=== Data types of each column: ===
vm_id               str
user_id             str
project_id          str
image_ref           str
vcpus           float64
memory_mb       float64
root_gb         float64
ephemeral_gb    float64
dtype: object

=== Summary statistics: ===
               vcpus      memory_mb      root_gb  ephemeral_gb
count     611.000000     611.000000   611.000000    585.000000
mean      809.369885   77652.569558    81.235679     63.290598
std      8655.992695  114445.519382   147.451532    118.689986
min         1.000000      10.000000     0.000000      0.000000
25%         4.000000    7000.000000    20.000000      0.000000
50%         8.000000   15000.000000    30.000000      0.000000
75%        64.000000   94000.000000    40.000000     30.000000
max    192000.000000  370000.000000  1000.000000    500.000000

### Checking for NULL values

In [18]:
# checking if any columns have only missing values
missing_columns = all_nodes.columns[all_nodes.isnull().all()]
print(f"Columns with only missing values: {missing_columns.tolist()}")

Columns with only missing values: []

In [21]:
for df, name in [(node_groups, "Nodes Hardware Data"), (all_nodes, "All Nodes Data"), (vm_hardware, "VM Hardware Data")]:
    print(f"\n=== {name} ===")
    print("\n=== Null values per column: ===")
    print(df.isnull().sum())

=== Nodes Hardware Data ===

=== Null values per column: ===
node_group              0
model                   0
form_factor             0
#sockets                0
cpu                     0
#cores_per_socket       0
#threads_per_core       0
memory_type             0
memory_manufacturer     0
memory_used_slots       0
memory_total_size_GB    0
#gpus                   0
#gpu_model              0
#ethernet_nics          0
ethernet_nic_model      0
#infiniband_nics        0
infiniband_nic_model    0
#disks                  0
disk_vendor             0
disk_model              1
disk_type               0
disk_size_GB            0
#fans                   0
#power_supplies         0
rated_power             0
dtype: int64

=== All Nodes Data ===

=== Null values per column: ===
timestamp                             0
node_name                             0
node_group                            0
cpu_usage_percent                436725
cpu_idle_percent                 436725
cpu_nice_percent                 436725
cpu_interrupt_percent            436725
cpu_softirq_percent              436725
cpu_steal_percent                436725
cpu_system_percent               436725
cpu_user_percent                 436725
cpu_wait_percent                 436725
load_shortterm_percent           436668
load_midterm_percent             436668
load_longterm_percent            436668
num_processes_total              436836
num_processes_blocked            436846
num_processes_paging             436838
num_processes_running            436846
num_processes_sleeping           436841
num_processes_stopped            436845
num_processes_zombie             436847
memory_total_bytes               436671
memory_free_bytes                436671
memory_used_bytes                436671
memory_buffered_bytes            436671
memory_cached_bytes              436671
memory_slab_recl_bytes           436671
memory_slab_unrecl_bytes         436671
disk_total_bytes                 436687
disk_free_bytes                  436687
disk_used_bytes                  436690
disk_reserved_bytes              436690
network_bw_rx_b/s                442123
network_bw_tx_b/s                442125
ipmi_system_power_watts          559333
rapl_power_total_watts           487176
rapl_power_package_0_watts       487230
rapl_power_package_1_watts       487221
rapl_power_dram_0_watts          487224
rapl_power_dram_1_watts          487213
rapl_power_cores_0_watts        6889945
rapl_power_cores_1_watts        6889945
scaphandre_power_total_watts    2526498
ipmi_cpu_power_watts            1566861
ipmi_memory_power_watts         1566871
ipmi_fan_power_watts            2525434
ipmi_psu1_ac_in_power_watts     2525435
ipmi_psu2_ac_in_power_watts     2525432
ipmi_psu1_dc_out_power_watts    2525431
ipmi_psu2_dc_out_power_watts    2525431
dtype: int64

=== VM Hardware Data ===

=== Null values per column: ===
vm_id            0
user_id          0
project_id       0
image_ref        0
vcpus            0
memory_mb        0
root_gb          0
ephemeral_gb    26
dtype: int64